name: main

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run ci
      - run: npm run build --if-present
        name: Build
      - run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          yarn install --frozen-lockfile
          yarn build
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}